spring:
  datasource:
    url: jdbc:postgresql://mypsqldb-vedant3532-7705.a.aivencloud.com:15768/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_LPyJ97Vf462EWgqQcQZ
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 102113765632-emdul139m3scdj54um431i0ptmc75sb5.apps.googleusercontent.com
            client-secret: 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

server:
  port: 8080
